import placeholder from '../../Assets/Images/placeholder.png'
export const blogData =[
    {image:placeholder, title:"Blog title heading will go here", category:"PCM", career:"Lawyer",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:placeholder, title:"Blog title heading will go here", category:"PCB", career:"Lawyer",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:placeholder, title:"Blog title heading will go here", category:"Commerce", career:"Lawyer",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:placeholder, title:"Blog title heading will go here", category:"Arts", career:"Lawyer",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:placeholder, title:"Blog title heading will go here", category:"PCM", career:"Lawyer",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:placeholder, title:"Blog title heading will go here", category:"PCM", career:"Lawyer",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:placeholder, title:"Blog title heading will go here", category:"PCM", career:"Lawyer",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:placeholder, title:"Blog title heading will go here", category:"PCM", career:"Lawyer",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:placeholder, title:"Blog title heading will go here", category:"PCM", career:"Lawyer",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:placeholder, title:"Blog title heading will go here", category:"PCM", career:"Lawyer", 
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    }
  ]